name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17]  # Running builds on both Java 11 and 17

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Lint (Detekt for Kotlin)
      run: ./gradlew detekt

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: app/build/outputs/**  # Upload all output files (APK, AAB, etc.)
        retention-days: 30  # Optional: Customize the retention period
